- type: replace
  path: /instance_groups/name=web/azs
  value: ((azs))
- type: replace
  path: /instance_groups/name=worker/azs
  value: ((azs))
- type: replace
  path: /instance_groups/name=iaas-worker/azs
  value: ((azs))

- type: replace
  path: /instance_groups/name=web/vm_extensions?
  value: ((web_vm_extensions))
- type: replace
  path: /instance_groups/name=worker/vm_extensions?
  value: ((worker_vm_extensions))
- type: replace
  path: /instance_groups/name=iaas-worker/vm_extensions?
  value: ((iaas_worker_vm_extensions))

- type: replace
  path: /update/update_watch_time?
  value: 120000

- type: replace
  path: /update/canary_watch_time?
  value: 120000

- type: replace
  path: /instance_groups/name=web/properties/default_check_interval?
  value: 3m

- type: replace
  path: /instance_groups/name=web/properties/default_check_interval_with_webhook?
  value: 3m

- type: replace
  path: /instance_groups/name=web/properties/lidar_scanner_interval?
  value: 10m
